# Generated by Django 5.2.12 on 2026-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_flowassertion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdiagnostic',
            name='diagnostic_id',
            field=models.CharField(max_length=40),
        ),
    ]
