# Generated by Django 5.2.12 on 2026-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_changeregisteritem_external_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeregisteritem',
            name='item_kind',
            field=models.CharField(blank=True, choices=[('rev_proc', 'Revenue Procedure'), ('notice', 'Notice'), ('rev_rul', 'Revenue Ruling'), ('announcement', 'Announcement'), ('federal_register', 'Federal Register Document'), ('irb_bulletin', 'IRB Bulletin'), ('cfr_section', '26 CFR Section Amendment'), ('draft_form', 'Draft Form/Instruction'), ('final_form', 'Final Form/Instruction'), ('court_opinion', 'Court Opinion'), ('public_law', 'Public Law'), ('state_page', 'State DOR Page Change')], help_text='What kind of publication this is — lets the digest group by type.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='changeregisteritem',
            name='published_date',
            field=models.DateField(blank=True, help_text='When the AUTHORITY published it — distinct from detected_at (when we noticed).', null=True),
        ),
        migrations.AddField(
            model_name='changeregisteritem',
            name='relevance_score',
            field=models.IntegerField(blank=True, db_index=True, help_text='0-100 perimeter relevance. ORDERS the digest; NEVER gates creation — an unscored or low-scoring item is still recorded, just below the line. Suppressing a real change at write time is the silent error the prime directive forbids. Null = never scored.', null=True),
        ),
        migrations.AddField(
            model_name='changeregisteritem',
            name='relevance_signals',
            field=models.JSONField(blank=True, default=list, help_text="Why it scored what it scored: [{'kind':'form','value':'4797','via':'TaxForm','weight':40}]. Makes a score auditable instead of a bare number."),
        ),
        migrations.AddField(
            model_name='changeregisteritem',
            name='source_url',
            field=models.TextField(blank=True, help_text='Direct link to the authority document. Previously buried in `summary` prose.', null=True),
        ),
        migrations.AddField(
            model_name='sourcefeeddefinition',
            name='arm_command',
            field=models.CharField(blank=True, default='', help_text="Management command that owns this feed, e.g. 'poll_source_pages'. Blank = documentation-only.", max_length=60),
        ),
        migrations.AddField(
            model_name='sourcefeeddefinition',
            name='last_checksum_sha256',
            field=models.CharField(blank=True, help_text='Page-diff state. Deliberately NOT AuthorityVersion.checksum_sha256 — that tracks authority DOCUMENTS; this tracks an arbitrary watched page. Null = no baseline yet (first poll opens nothing).', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sourcefeeddefinition',
            name='last_content',
            field=models.TextField(blank=True, help_text='Normalized text of the last poll, so a diff can show what was ADDED.', null=True),
        ),
        migrations.AddField(
            model_name='sourcefeeddefinition',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcefeeddefinition',
            name='last_result_note',
            field=models.TextField(blank=True, help_text="Last run's outcome or error — feeds the digest's arm-health section.", null=True),
        ),
        migrations.AddField(
            model_name='sourcefeeddefinition',
            name='selector_config',
            field=models.JSONField(blank=True, default=dict, help_text="Per-feed parser knobs, e.g. {'content_regex': ..., 'strip_patterns': [...], 'max_pages': 2}."),
        ),
        migrations.AlterField(
            model_name='changeregisteritem',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, help_text="Stable dedup key for automated detection. NAMESPACE new arms with a prefix so keys from different feeds can never collide: 'DROP:rp-26-28.pdf', 'CFR26:1.199A-3@2026-07-09', 'DFT:f1040--dft.pdf@2026-08-04', 'CL:<cluster_id>', 'PAGE:<feed>@<sha12>'. The two original arms are unprefixed (FR document_number, 'IRB-YYYY-NN') and do not collide with the prefixes.", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sourcefeeddefinition',
            name='feed_type',
            field=models.CharField(choices=[('html_index', 'HTML Index'), ('pdf_list', 'PDF List'), ('xml_repo', 'XML Repository'), ('manual_upload', 'Manual Upload'), ('json_api', 'JSON API'), ('html_page', 'HTML Page (diff)'), ('directory_index', 'Directory Index')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='changeregisteritem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__isnull', False)), fields=('external_ref',), name='uniq_change_register_external_ref'),
        ),
    ]
