# Generated by Django 5.2.12 on 2026-08-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_change_feeds_phase0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdictionconformitysource',
            name='decoupled_items',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of items where the state diverges from federal. Canonical entry shape (normalized 2026-08-05 — campaign D-8): {item, federal_treatment, state_treatment, authority_source_code, notes}. `authority_source_code` is the AuthoritySource.source_code string, NOT a UUID — UUIDs differ per environment and the downstream consumer (delvio-tax) resolves authority by code everywhere else in the export package.'),
        ),
        migrations.AddConstraint(
            model_name='jurisdictionconformitysource',
            constraint=models.UniqueConstraint(fields=('jurisdiction_code', 'tax_year'), name='uniq_conformity_jurisdiction_taxyear'),
        ),
    ]
