# Generated by Django 5.2.12 on 2026-08-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_alter_jurisdictionconformitysource_decoupled_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritysource',
            name='source_type',
            field=models.CharField(choices=[('code_section', 'IRC Section'), ('regulation', 'Treasury Regulation'), ('case_law', 'Case Law'), ('irs_internal_procedure', 'IRS Internal Procedure (IRM)'), ('official_form', 'Official Form'), ('official_instruction', 'Form Instructions'), ('official_publication', 'IRS Publication'), ('official_notice', 'IRS Notice'), ('official_revenue_ruling', 'Revenue Ruling'), ('official_revenue_procedure', 'Revenue Procedure'), ('mef_schema', 'MeF XML Schema'), ('mef_business_rule', 'MeF Business Rule'), ('mef_release_memo', 'MeF Release Memo'), ('state_statute', 'State Statute'), ('state_regulation', 'State Regulation'), ('state_form', 'State Form'), ('state_instruction', 'State Instructions'), ('state_efile_spec', 'State E-File Spec'), ('state_vendor_guide', 'State Vendor Guide'), ('state_conformity_notice', 'State Conformity Notice'), ('internal_memo', 'Internal Memo'), ('internal_example', 'Worked Example'), ('internal_test_case', 'Internal Test Case')], max_length=40),
        ),
    ]
